# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create and Deploy Prod HTML site
# Includes building automatically when either of the relevant JSON files update on the main branch or on the push of a button
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
         token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        init-shell: bash
        environment-file: environment.yml
    - name: create HTML file
      shell: bash -l {0}
      run: |
        python build_webpage.py
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/main'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: deploy # The folder the action should deploy.
        repository-name: mathewbiddle/check_websites
  #      token: ${{ secrets.API_TOKEN_GITHUB }}
